project_id = "cdqmnfrubfdfjniiunim"

[functions.generate-insights]
verify_jwt = true

[functions.calculate-net-salary]
verify_jwt = true

[functions.admin-users]
enabled = true
verify_jwt = true
import_map = "./functions/admin-users/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-users/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-users/*.html" ]

[functions.admin-metrics]
enabled = true
verify_jwt = true
import_map = "./functions/admin-metrics/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-metrics/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-metrics/*.html" ]

[functions.admin-logs]
enabled = true
verify_jwt = true
import_map = "./functions/admin-logs/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-logs/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-logs/*.html" ]
